export const CONTEXT_STRATEGIES = {
  fullContext: {
    id: 'fullContext',
    label: 'Full Context',
    description: 'Put all available documents or history directly into the model context.',
    advantage: 'No retrieval miss if everything fits.',
    risk: 'High cost, distractors, lost-in-middle, and latency.',
    coverage: 94,
    distractors: 82,
    cost: 91,
  },
  rag: {
    id: 'rag',
    label: 'RAG',
    description: 'Retrieve top relevant chunks, then answer from them.',
    advantage: 'Lower cost and fewer distractors.',
    risk: 'Can miss required evidence or retrieve stale chunks.',
    coverage: 68,
    distractors: 32,
    cost: 34,
  },
  compressedMemory: {
    id: 'compressedMemory',
    label: 'Compressed Memory',
    description: 'Summarize or store structured memory instead of raw context.',
    advantage: 'Very low token cost for repeated use.',
    risk: 'Can drop exact facts or preserve stale summaries.',
    coverage: 51,
    distractors: 20,
    cost: 14,
  },
  hybrid: {
    id: 'hybrid',
    label: 'Hybrid RAG + Long Context',
    description: 'Retrieve and rerank a broader evidence set, then use long context to reason across it.',
    advantage: 'Balances recall and distractor control.',
    risk: 'More system complexity and still depends on retrieval quality.',
    coverage: 86,
    distractors: 44,
    cost: 58,
  },
};

export const LONG_CONTEXT_TABS = [
  {
    id: 'strategy-map',
    label: 'Strategy Map',
    title: 'Long Context Map',
    purpose: 'Choose whether to show everything, retrieve selected evidence, compress memory, or combine strategies.',
    misconception: 'A bigger context window is not a substitute for retrieval, ranking, compression, or evaluation.',
    lab: 'Choose a strategy for 200 legal documents with 3 relevant clauses and citation requirements.',
  },
  {
    id: 'claimed-effective',
    label: 'Claimed vs Effective',
    title: 'Claimed Window vs Effective Context',
    purpose: 'Separate advertised input length from the context a model can reliably use for a task.',
    misconception: 'A model may fit 1M tokens but still fail a multi-hop task that links subtle facts.',
    lab: 'Compare single-needle, semantic needle, and multi-hop success as the same prompt grows.',
  },
  {
    id: 'pretraining',
    label: 'Training vs Extrapolation',
    title: 'Long-Context Pretraining vs Extrapolation',
    purpose: 'Compare native long-context training, long-context post-training, and inference-time stretching.',
    misconception: 'Extrapolating a model to longer context is not the same as training it to reason over long context.',
    lab: 'Move from 32K training to 1M inference and identify which risks increase.',
  },
  {
    id: 'position',
    label: 'RoPE / iRoPE / NoPE',
    title: 'Position Encoding at Frontier Lengths',
    purpose: 'Show how RoPE scaling, iRoPE-inspired layer mixes, and NoPE-style layers reduce position stress.',
    misconception: 'Position tricks help address far-away tokens; they do not guarantee reasoning over them.',
    lab: 'Tune RoPE scale and NoPE layer fraction until aliasing risk falls without losing local order.',
  },
  {
    id: 'kv-cost',
    label: 'KV Cache Cost',
    title: 'KV Cache and Attention Cost at 1M+',
    purpose: 'Connect long context to K/V memory, decode reads, prompt cost, latency, and concurrency.',
    misconception: 'Long context is an inference and product-cost capability, not only a model capability.',
    lab: 'Compare MHA, GQA, MLA, compressed memory, and RAG-packed prompts under 64 concurrent users.',
  },
  {
    id: 'lost-middle',
    label: 'Lost in the Middle',
    title: 'Lost in the Middle',
    purpose: 'Demonstrate why evidence position matters inside a long prompt.',
    misconception: 'If the model misses middle evidence, adding more context can make the problem worse.',
    lab: 'Move the relevant evidence from start to middle to end and choose a mitigation.',
  },
  {
    id: 'needle-limits',
    label: 'Needle Limits',
    title: 'Needle-in-Haystack Limitations',
    purpose: 'Distinguish literal single-fact lookup from semantic, multi-needle, conflicting, and chained evidence tasks.',
    misconception: 'Passing needle-in-haystack does not prove broad long-context reasoning.',
    lab: 'Run single-needle, multi-needle, and semantic-needle tasks and explain the performance gap.',
  },
  {
    id: 'multi-hop',
    label: 'Multi-Hop',
    title: 'Multi-Hop Long-Context Reasoning',
    purpose: 'Track intermediate state across facts scattered through a large context.',
    misconception: 'Multi-hop long-context reasoning is not just finding a passage.',
    lab: 'Find nodes two hops away in a graph whose edges are scattered through the prompt.',
  },
  {
    id: 'compression',
    label: 'Compression',
    title: 'Context Compression and Memory Tools',
    purpose: 'Show how summaries, entity memory, episodic memory, and task memory save tokens while risking fact loss.',
    misconception: 'Memory is compressed context, not perfect context.',
    lab: 'Compress a long conversation and preserve the exact fact needed by a later question.',
  },
  {
    id: 'rag-hybrid',
    label: 'RAG vs Full vs Hybrid',
    title: 'RAG vs Full Context vs Hybrid',
    purpose: 'Compare evidence recall, distractor load, cost, latency, and citation quality across strategies.',
    misconception: 'RAG and long context are not enemies; strong systems often retrieve first, then reason over selected evidence.',
    lab: 'Tune top-k, reranking, and context window to maximize relevant facts while limiting distractors.',
  },
  {
    id: 'evaluation',
    label: 'Evaluation',
    title: 'Evaluation and Product Tradeoffs',
    purpose: 'Build a scorecard beyond single-needle retrieval: MRCR, Graphwalks, grounding, cost, latency, and abstention.',
    misconception: 'Long-context quality is application-specific.',
    lab: 'Choose an evaluation suite for legal review, codebase agents, research, support, or personal memory.',
  },
];

export const LONG_CONTEXT_FAILURES = [
  {
    id: 'lost-in-middle',
    label: 'Lost in the middle',
    symptom: 'Model misses evidence buried in the middle of a long prompt.',
    mitigation: 'Rerank, reorder, summarize, cite evidence, or use position-aware packing.',
  },
  {
    id: 'retrieval-miss',
    label: 'Retrieval miss',
    symptom: 'RAG fails to include required evidence.',
    mitigation: 'Improve query rewriting, top-k, chunking, reranking, and recall evaluation.',
  },
  {
    id: 'compression-loss',
    label: 'Compression loss',
    symptom: 'Summary or memory drops an exact detail needed later.',
    mitigation: 'Store structured facts, preserve citations, and allow raw-evidence fallback.',
  },
  {
    id: 'multi-hop-failure',
    label: 'Multi-hop failure',
    symptom: 'Evidence pieces are present but not linked correctly.',
    mitigation: 'Use scratchpads, graph/state tracking, and multi-hop evaluations.',
  },
  {
    id: 'distractor-confusion',
    label: 'Distractor confusion',
    symptom: 'Similar irrelevant evidence wins over the true evidence.',
    mitigation: 'Use reranking, claim-level citation checks, and contradiction detection.',
  },
];

export const PAPER_CARDS = [
  {
    title: 'GPT-4.1',
    signal: '1M-token context, MRCR, Graphwalks, and long-document use cases.',
    interpretation: 'Frontier long context is moving from one-fact retrieval toward disambiguation and multi-hop reasoning.',
  },
  {
    title: 'Llama 4 Scout',
    signal: '10M-token context, 256K training context, interleaved attention, iRoPE, and NoPE-style layers.',
    interpretation: 'Very long context depends on architecture, training, position strategy, and inference extensions.',
  },
  {
    title: 'Lost in the Middle',
    signal: 'Relevant information position changes task performance.',
    interpretation: 'A model does not necessarily use every token position equally well.',
  },
  {
    title: 'NoLiMa / U-NIAH / LongBench',
    signal: 'Semantic needles, multi-needle settings, RAG comparisons, and broad long-context task suites.',
    interpretation: 'Long-context evaluation must test reasoning, distractors, grounding, and task families.',
  },
];
