export const coreMlLessons = {
  'train-validation-test-split': {
    id: 'train-validation-test-split',
    title: 'Train / Validation / Test Split',
    eyebrow: 'Honest evaluation',
    summary: 'A model learns on training data, gets tuned on validation data, and earns its final report card on test data it never shaped.',
    equation: 'D = D_train + D_val + D_test',
    intuition: 'Think of training as practice problems, validation as coaching feedback, and test as the exam. If the exam leaks into practice, the score stops meaning what you think it means.',
    mechanism: [
      'Shuffle examples before splitting so each slice resembles the same population.',
      'Fit parameters only on the training set.',
      'Use validation results to choose model class, hyperparameters, thresholds, or stopping time.',
      'Touch the test set once at the end for an honest generalization estimate.',
    ],
    controls: [
      { id: 'validation', label: 'Validation %', min: 10, max: 30, step: 5, defaultValue: 20 },
      { id: 'test', label: 'Test %', min: 10, max: 30, step: 5, defaultValue: 20 },
    ],
    check: 'If you repeatedly pick the best model by looking at test performance, what set did the test data secretly become?',
    answer: 'It became another validation set, so the final score is optimistic.',
  },
  overfitting: {
    id: 'overfitting',
    title: 'Overfitting',
    eyebrow: 'Generalization gap',
    summary: 'Overfitting appears when training error keeps improving but validation error turns upward because the model is learning quirks of the training sample.',
    equation: 'train error down, validation error up',
    intuition: 'A memorized answer key can ace yesterday’s worksheet and still fail tomorrow’s variant.',
    mechanism: [
      'Small models may underfit because they cannot express the real pattern.',
      'A well-sized model captures the signal and leaves most random noise alone.',
      'An overly flexible model bends around individual training points.',
      'The warning sign is a widening gap between training and validation performance.',
    ],
    controls: [
      { id: 'complexity', label: 'Model complexity', min: 1, max: 10, step: 1, defaultValue: 6 },
    ],
    check: 'Why is training loss alone a bad model-selection signal?',
    answer: 'It rewards memorization, so it can improve even while validation performance gets worse.',
  },
  'logistic-regression': {
    id: 'logistic-regression',
    title: 'Logistic Regression',
    eyebrow: 'Binary classification',
    summary: 'Logistic regression turns a linear score into a probability with the sigmoid curve, then applies a threshold to make a class decision.',
    equation: 'P(y=1|x) = sigmoid(w*x + b)',
    intuition: 'The linear model creates a score; sigmoid compresses it into a calibrated-looking 0-to-1 scale.',
    mechanism: [
      'Compute a logit from features using weights and bias.',
      'Pass the logit through sigmoid to produce a probability.',
      'Compare the probability with a threshold to choose class 0 or class 1.',
      'Train with binary cross-entropy so confident wrong predictions are penalized heavily.',
    ],
    controls: [
      { id: 'weight', label: 'Weight', min: 0.4, max: 2.4, step: 0.1, defaultValue: 1.2 },
      { id: 'bias', label: 'Bias', min: -2, max: 2, step: 0.25, defaultValue: 0 },
      { id: 'threshold', label: 'Threshold', min: 0.2, max: 0.8, step: 0.05, defaultValue: 0.5 },
    ],
    check: 'What changes when you raise the threshold from 0.5 to 0.7?',
    answer: 'The model predicts fewer positives, usually increasing precision and lowering recall.',
  },
  'classification-metrics': {
    id: 'classification-metrics',
    title: 'Classification Metrics',
    eyebrow: 'Mistake accounting',
    summary: 'Classification metrics translate model decisions into counts and tradeoffs, especially when false positives and false negatives have different costs.',
    equation: 'precision = TP / (TP + FP), recall = TP / (TP + FN)',
    intuition: 'Accuracy asks “how often right?” Precision asks “when it says positive, is it right?” Recall asks “did it find the positives?”',
    mechanism: [
      'Choose a threshold that converts probabilities into class labels.',
      'Count true positives, false positives, false negatives, and true negatives.',
      'Compute precision, recall, F1, and accuracy from those counts.',
      'Move the threshold to reveal the tradeoff instead of trusting one default cutoff.',
    ],
    controls: [
      { id: 'threshold', label: 'Decision threshold', min: 0.2, max: 0.8, step: 0.05, defaultValue: 0.5 },
    ],
    check: 'In a rare-disease screen, why might recall matter more than raw accuracy?',
    answer: 'Missing true positives can be costly, while accuracy may stay high by mostly predicting the common negative class.',
  },
  regularization: {
    id: 'regularization',
    title: 'Regularization',
    eyebrow: 'Complexity penalty',
    summary: 'Regularization adds a complexity cost to the loss so the model prefers smoother, smaller, more generalizable solutions.',
    equation: 'loss = data loss + lambda * penalty',
    intuition: 'It is a budgeting rule: spend model complexity only when it buys enough real predictive value.',
    mechanism: [
      'Train the model with both data error and a penalty term.',
      'Increasing lambda shrinks parameters and smooths decision boundaries.',
      'Too little penalty can overfit; too much penalty can underfit.',
      'Tune lambda on validation data, then evaluate once on the test set.',
    ],
    controls: [
      { id: 'lambda', label: 'Penalty strength', min: 0, max: 10, step: 1, defaultValue: 3 },
    ],
    check: 'Why can strong regularization hurt both training and validation performance?',
    answer: 'It can force the model to be too simple to capture the real signal.',
  },
};
