export const CODING_AGENT_STAGES = [
  {
    id: 'understand',
    label: 'Understand issue',
    tool: 'issue reader',
    output: 'symptom, expected behavior, constraints',
    risk: 'misread requirement',
  },
  {
    id: 'navigate',
    label: 'Navigate repo',
    tool: 'grep, symbol search, file open',
    output: 'relevant files and tests',
    risk: 'wrong file or missed dependency',
  },
  {
    id: 'plan',
    label: 'Plan minimal change',
    tool: 'planner, memory file',
    output: 'small patch hypothesis',
    risk: 'overbroad or vague plan',
  },
  {
    id: 'edit',
    label: 'Edit files',
    tool: 'patch editor',
    output: 'working-tree diff',
    risk: 'unrelated changes',
  },
  {
    id: 'test',
    label: 'Run tests',
    tool: 'shell, test runner, linter',
    output: 'target and regression evidence',
    risk: 'flaky or incomplete tests',
  },
  {
    id: 'review',
    label: 'Review diff',
    tool: 'git diff, reviewer',
    output: 'patch confidence and caveats',
    risk: 'missed regression',
  },
  {
    id: 'submit',
    label: 'Submit PR',
    tool: 'git, PR tool',
    output: 'reviewable change request',
    risk: 'premature submission',
  },
];

export const MODULES = [
  {
    id: 'system-map',
    label: 'System Map',
    title: 'Agentic Coding Overview',
    purpose: 'Show the full controlled loop from issue intake to patch evidence.',
    misconception: 'A coding agent is not just a chat response. It is a loop over repository state, actions, observations, and validation.',
    lab: 'Given a bug report, identify what the agent must know before it is allowed to edit.',
  },
  {
    id: 'swe-bench',
    label: 'SWE-bench Loop',
    title: 'SWE-bench-Style Task Loop',
    purpose: 'Evaluate whether a patch fixes the issue and preserves unrelated behavior.',
    misconception: 'Passing the target test is not enough; PASS_TO_PASS behavior still has to survive.',
    lab: 'Classify a patch as resolved, plausible-but-risky, or regressed using FAIL_TO_PASS and PASS_TO_PASS results.',
  },
  {
    id: 'repo-navigation',
    label: 'Repo Navigation',
    title: 'Repo Navigation and Context Building',
    purpose: 'Treat repo understanding as search, retrieval, and code reasoning under a context budget.',
    misconception: 'Large context helps, but irrelevant files still distract and consume budget.',
    lab: 'Use issue keywords, stack trace lines, and test names to choose the next three files to open.',
  },
  {
    id: 'plan-edit-test',
    label: 'Plan-Edit-Test',
    title: 'Plan, Edit, Run Tests, Patch, Review',
    purpose: 'Make the smallest coherent change, observe the test signal, and revise.',
    misconception: 'More editing is not more progress; good patches are often narrow.',
    lab: 'Approve or reject a plan based on whether it reproduces the bug before changing behavior.',
  },
  {
    id: 'sandbox',
    label: 'Sandbox Execution',
    title: 'Sandboxed Execution and Test Running',
    purpose: 'Control commands, network, secrets, and side effects while preserving reproducibility.',
    misconception: 'Sandboxing is not only security; it also makes retries and rollback safe.',
    lab: 'Classify shell commands as safe, approval-required, or blocked.',
  },
  {
    id: 'diff-review',
    label: 'Diff Review',
    title: 'Patch Generation and Diff Review',
    purpose: 'Judge reviewability by changed files, changed lines, tests, and rationale.',
    misconception: 'A patch that compiles is not automatically reviewable.',
    lab: 'Compare a minimal fix, an overbroad refactor, and a test-gaming patch.',
  },
  {
    id: 'memory',
    label: 'Memory Files',
    title: 'Memory Files and Agent Manifests',
    purpose: 'Use AGENTS.md, CLAUDE.md, rules, and project notes to encode local conventions.',
    misconception: 'Memory files help only when they are accurate, scoped, and current.',
    lab: 'Write three project rules that would prevent wrong test commands and generated-file edits.',
  },
  {
    id: 'checkpoints',
    label: 'Checkpoints',
    title: 'Checkpoints, Rollback, and State',
    purpose: 'Keep recoverable states before edits, risky commands, and broad retries.',
    misconception: 'Version control is part of the reasoning loop, not only the final packaging step.',
    lab: 'Choose the rollback point after a regression appears in an unrelated module.',
  },
  {
    id: 'multi-agent',
    label: 'Multi-Agent Review',
    title: 'Multi-Agent Coding Review',
    purpose: 'Separate planning, implementation, testing, security, and review concerns when the risk justifies it.',
    misconception: 'More agents add coverage but also coordination cost and false objections.',
    lab: 'Identify which role should catch a missing regression test.',
  },
  {
    id: 'regression-filtering',
    label: 'Regression Tests',
    title: 'Regression Test Filtering',
    purpose: 'Balance targeted confidence against suite runtime, flakiness, and dependency distance.',
    misconception: 'A narrow passing test is a signal, not a proof of safety.',
    lab: 'Pick tests under a ten-minute budget after a two-file parser patch.',
  },
  {
    id: 'approval',
    label: 'Human Approval',
    title: 'Human Approval Boundaries',
    purpose: 'Define when edits, shell commands, network access, PRs, and deployments require consent.',
    misconception: 'Approval is the boundary between agent autonomy and user authority.',
    lab: 'Configure approval gates for secrets, package installs, auth code, and PR submission.',
  },
  {
    id: 'failure-modes',
    label: 'Failure Modes',
    title: 'Coding Agent Failure Modes',
    purpose: 'Recognize wrong-file edits, overbroad refactors, test gaming, regressions, unsafe commands, and scope drift.',
    misconception: 'A capable coding model can still be an unsafe coding agent if the environment permits out-of-scope actions.',
    lab: 'Diagnose whether a failed run came from wrong context, bad plan, bad patch, incomplete tests, or approval failure.',
  },
];

export const FAILURE_SCENARIOS = [
  {
    id: 'wrong-file',
    label: 'Wrong file edited',
    symptom: 'Patch does not touch the true source of the bug.',
    mitigation: 'Improve repo search, inspect stack trace, open tests first.',
    risk: 74,
  },
  {
    id: 'overbroad-refactor',
    label: 'Overbroad refactor',
    symptom: 'Many unrelated files changed for a narrow task.',
    mitigation: 'Enforce minimal diff, scope check, and approval gate.',
    risk: 82,
  },
  {
    id: 'test-gaming',
    label: 'Test gaming',
    symptom: 'Visible tests pass while intended behavior is violated.',
    mitigation: 'Require behavioral review, hidden tests, and spec checks.',
    risk: 69,
  },
  {
    id: 'regression',
    label: 'PASS_TO_PASS regression',
    symptom: 'Target bug is fixed but unrelated behavior breaks.',
    mitigation: 'Run affected-module and smoke regression tests.',
    risk: 76,
  },
  {
    id: 'unsafe-command',
    label: 'Unsafe command',
    symptom: 'Agent attempts destructive shell or external side effect.',
    mitigation: 'Sandbox commands and require explicit approval.',
    risk: 88,
  },
  {
    id: 'scope-creep',
    label: 'Scope drift',
    symptom: 'Agent does more than the requested task boundary.',
    mitigation: 'Compare every changed file against the issue scope.',
    risk: 80,
  },
];

export const PRODUCT_CARDS = [
  {
    title: 'SWE-bench Verified',
    signal: 'Repo + issue, patch generation, FAIL_TO_PASS and PASS_TO_PASS evaluation.',
    interpretation: 'Coding-agent evaluation is about resolving real issues without breaking existing behavior.',
  },
  {
    title: 'GPT-4.1',
    signal: 'Long context, coding reliability, diff following, and SWE-bench Verified reporting.',
    interpretation: 'Reliable repository comprehension and patch formatting are model-level ingredients.',
  },
  {
    title: 'Claude Code',
    signal: 'Repo mapping, terminal/IDE workflow, tests, PR submission, and approval gates.',
    interpretation: 'A coding agent is a workflow layer around a permissioned development environment.',
  },
  {
    title: 'Claude Sonnet 4.5',
    signal: 'Long-horizon coding focus, computer-use improvements, memory and permission infrastructure.',
    interpretation: 'Frontier coding systems are sustained control loops, not one-shot code completions.',
  },
];
