export const GRPO_CANDIDATES = [
  {
    id: 'A',
    label: 'Correct clean trace',
    isCorrect: 1,
    hasValidFormat: 1,
    tokenCount: 42,
    languageMixed: 0,
    summary: 'Solves x = 3 with clean final answer.',
  },
  {
    id: 'B',
    label: 'Wrong arithmetic',
    isCorrect: 0,
    hasValidFormat: 1,
    tokenCount: 38,
    languageMixed: 0,
    summary: 'Subtracts incorrectly and gives x = 4.',
  },
  {
    id: 'C',
    label: 'Correct but verbose',
    isCorrect: 1,
    hasValidFormat: 1,
    tokenCount: 140,
    languageMixed: 0,
    summary: 'Correct answer but uses unnecessary reasoning.',
  },
  {
    id: 'D',
    label: 'Correct malformed',
    isCorrect: 1,
    hasValidFormat: 0,
    tokenCount: 44,
    languageMixed: 0,
    summary: 'Correct math but no required final-answer marker.',
  },
  {
    id: 'E',
    label: 'Wrong and malformed',
    isCorrect: 0,
    hasValidFormat: 0,
    tokenCount: 20,
    languageMixed: 0,
    summary: 'Wrong answer and invalid format.',
  },
  {
    id: 'F',
    label: 'Correct concise',
    isCorrect: 1,
    hasValidFormat: 1,
    tokenCount: 30,
    languageMixed: 0,
    summary: 'Shortest clean correct solution.',
  },
  {
    id: 'G',
    label: 'Correct but language mixed',
    isCorrect: 1,
    hasValidFormat: 1,
    tokenCount: 55,
    languageMixed: 1,
    summary: 'Correct answer but mixes languages mid-trace.',
  },
  {
    id: 'H',
    label: 'Correct but overthinking',
    isCorrect: 1,
    hasValidFormat: 1,
    tokenCount: 220,
    languageMixed: 0,
    summary: 'Correct answer but extreme overthinking.',
  },
];

export const DEFAULT_GRPO_WEIGHTS = {
  correctnessWeight: 1.0,
  formatWeight: 0.1,
  languagePenalty: 0.2,
  lengthPenalty: 0.01,
  idealLength: 50,
};
