export const CONTEXT_LENGTHS = [4096, 32768, 128000, 1000000];
export const LAYER_OPTIONS = [12, 32, 80];
export const HIDDEN_OPTIONS = [1024, 4096, 8192];
export const PRECISION_BYTES = { fp16: 2, fp8: 1, int8: 1 };

export const ARCHITECTURE_FAMILIES = [
  {
    id: 'dense-transformer',
    name: 'Dense Transformer',
    shortName: 'Dense',
    activeCompute: 'high',
    kvMemory: 'high',
    contextScaling: 'quadratic attention',
    generationOrder: 'left-to-right',
    bestFor: 'strong general baseline',
    failureMode: 'expensive active compute and KV cache',
    tradeoff: 'Predictable full path, but every token pays for every block.',
    changes: ['Every token uses the same attention and dense FFN path.'],
    examples: ['Llama-style dense baselines', 'GPT-style dense baselines'],
    readInPaper: 'Look for decoder-only stacks, dense MLP/FFN blocks, and no router or expert count.',
  },
  {
    id: 'sparse-moe',
    name: 'Sparse MoE Transformer',
    shortName: 'MoE',
    activeCompute: 'medium',
    kvMemory: 'high',
    contextScaling: 'attention plus routing',
    generationOrder: 'left-to-right',
    bestFor: 'large capacity with lower active compute',
    failureMode: 'routing imbalance, communication, expert collapse',
    tradeoff: 'Large total capacity, but only selected experts run per token.',
    changes: ['Router selects top-k experts per token.', 'Total parameters can be much larger than active parameters.'],
    examples: ['DeepSeek-V3', 'Qwen3 MoE'],
    readInPaper: 'When a paper says active vs total parameters, look for expert routing.',
  },
  {
    id: 'attention-compressed',
    name: 'MHA / MQA / GQA / MLA',
    shortName: 'Attention',
    activeCompute: 'medium',
    kvMemory: 'low to high',
    contextScaling: 'compressed KV layout',
    generationOrder: 'left-to-right',
    bestFor: 'decode memory and bandwidth tradeoffs',
    failureMode: 'too much sharing can reduce head independence',
    tradeoff: 'Shrink cache reads while preserving enough attention expressiveness.',
    changes: ['Vary how query heads share K/V heads.', 'MLA caches compressed latent K/V information.'],
    examples: ['GQA inference models', 'DeepSeek-V2/V3-style MLA'],
    readInPaper: 'MLA, MQA, or GQA usually signals an inference memory design choice.',
  },
  {
    id: 'long-context',
    name: 'Long-Context Transformer',
    shortName: 'Long context',
    activeCompute: 'medium',
    kvMemory: 'high',
    contextScaling: 'full, local, retrieval, or compressed',
    generationOrder: 'left-to-right',
    bestFor: 'documents, codebases, video, agents',
    failureMode: 'lost-in-middle, high memory, latency',
    tradeoff: 'More evidence can fit, but retrieval over the evidence gets harder.',
    changes: ['Positioning, cache, retrieval, or memory strategy changes.'],
    examples: ['RoPE-scaled long-context LLMs', 'RAG plus long-context systems'],
    readInPaper: 'Long context claims should make you ask how memory, position, and distractors are handled.',
  },
  {
    id: 'state-space-hybrid',
    name: 'Hybrid Recurrent / State-Space',
    shortName: 'SSM hybrid',
    activeCompute: 'low',
    kvMemory: 'low',
    contextScaling: 'recurrent or hybrid',
    generationOrder: 'streaming left-to-right',
    bestFor: 'long streams and efficient sequence processing',
    failureMode: 'weaker direct content lookup unless hybridized',
    tradeoff: 'Linear sequence scaling, but compact state must choose what to keep.',
    changes: ['Maintains recurrent state instead of full pairwise attention.'],
    examples: ['Mamba-style selective SSMs', 'attention + SSM hybrids'],
    readInPaper: 'Selective state, recurrence, or scan kernels signal alternatives to full attention memory.',
  },
  {
    id: 'diffusion-language',
    name: 'Diffusion Language Model',
    shortName: 'Diffusion LM',
    activeCompute: 'medium',
    kvMemory: 'medium',
    contextScaling: 'iterative refinement',
    generationOrder: 'parallel refinement',
    bestFor: 'non-autoregressive generation research',
    failureMode: 'more refinement steps and newer sampling tools',
    tradeoff: 'Can refine many positions, but pays multiple forward passes.',
    changes: ['Iteratively refines masked tokens instead of only next-token decoding.'],
    examples: ['LLaDA-style language diffusion'],
    readInPaper: 'Masking, denoising, and reverse process language usually mean generation order changed.',
  },
  {
    id: 'omni-multimodal',
    name: 'Omni Multimodal Model',
    shortName: 'Omni',
    activeCompute: 'medium',
    kvMemory: 'medium',
    contextScaling: 'multimodal token budget',
    generationOrder: 'multimodal stream',
    bestFor: 'real-time assistants and multimodal agents',
    failureMode: 'alignment, latency, grounding, token budget',
    tradeoff: 'Shared reasoning across modalities, but every modality has its own encoder and budget pressure.',
    changes: ['Text, image, audio, and video become shared model inputs or outputs.'],
    examples: ['Qwen3-Omni-style Thinker-Talker systems'],
    readInPaper: 'Omni claims should make you look for modality encoders, shared thinker blocks, and output decoders.',
  },
];

export const FAMILY_BY_ID = Object.fromEntries(ARCHITECTURE_FAMILIES.map((family) => [family.id, family]));

export const ATTENTION_MODES = {
  MHA: {
    label: 'MHA',
    kvHeads: (queryHeads) => queryHeads,
    description: 'Every query head owns its own key and value head.',
    independence: 100,
    complexity: 'largest classic KV cache',
  },
  GQA: {
    label: 'GQA',
    kvHeads: (queryHeads) => Math.max(2, Math.round(queryHeads / 4)),
    description: 'Groups of query heads share key and value heads.',
    independence: 76,
    complexity: 'middle ground',
  },
  MQA: {
    label: 'MQA',
    kvHeads: () => 1,
    description: 'All query heads share one key and value head.',
    independence: 48,
    complexity: 'smallest classic KV cache',
  },
  MLA: {
    label: 'MLA',
    kvHeads: () => 0,
    description: 'K/V information is cached as compressed latent vectors.',
    independence: 82,
    complexity: 'compressed latent cache with projection cost',
  },
};

export const PAPER_SIGNAL_CARDS = [
  {
    title: 'DeepSeek-V3',
    signals: 'MoE, MLA, multi-token prediction',
    readAs: 'sparse capacity plus compressed attention memory',
    question: 'What bottleneck is solved: active compute, KV memory, or both?',
  },
  {
    title: 'Qwen3',
    signals: 'dense and MoE family, thinking budget',
    readAs: 'architecture variants plus inference-time compute control',
    question: 'Which part is model architecture and which part is decoding behavior?',
  },
  {
    title: 'Mamba',
    signals: 'selective state-space, linear sequence scaling',
    readAs: 'recurrent/state alternative to full pairwise attention',
    question: 'What information must the recurrent state keep or forget?',
  },
  {
    title: 'LLaDA',
    signals: 'masked diffusion language modeling',
    readAs: 'generation order changes from left-to-right to denoising',
    question: 'How many refinement steps replace one next-token loop?',
  },
  {
    title: 'Qwen3-Omni',
    signals: 'Thinker-Talker MoE, text/image/audio/video',
    readAs: 'omni multimodal input/output architecture',
    question: 'Where do modalities fuse, and what output head is active?',
  },
];

export const COMPARISON_ROWS = [
  ['Dense Transformer', 'Every token uses same full block', 'Simple, strong, predictable', 'Expensive active compute'],
  ['Sparse MoE', 'Token routes to selected experts', 'Huge capacity with lower active compute', 'Routing imbalance and communication'],
  ['MHA', 'Every head has own K/V', 'Maximum head independence', 'Large KV cache'],
  ['MQA', 'Many query heads share one K/V', 'Lower decode memory and bandwidth', 'More sharing, possible quality loss'],
  ['GQA', 'Groups of query heads share K/V', 'Middle ground between MHA and MQA', 'Group choice matters'],
  ['MLA', 'K/V compressed into latent state', 'Much smaller KV cache', 'Projection and implementation cost'],
  ['Long-context Transformer', 'Position or context strategy changes', 'More evidence can fit', 'Lost-in-middle, memory, latency'],
  ['SSM / recurrent hybrid', 'Maintains recurrent state', 'Linear sequence scaling', 'Weaker direct content lookup unless hybridized'],
  ['Diffusion LM', 'Iterative token refinement', 'Parallel or non-left-to-right generation', 'More steps, newer ecosystem'],
  ['Omni multimodal', 'Many modalities enter shared model', 'Unified perception and generation', 'Alignment, latency, token budget'],
];

export const QUESTION_AXES = [
  'How much of the model is active per token?',
  'How much memory is needed during decoding?',
  'How does the model access earlier context?',
  'Does it generate left-to-right or by iterative refinement?',
  'Can it consume or produce multiple modalities?',
  'What tradeoff did the architecture buy?',
];
